### ISSUE TITLE
Shopware Datetime Anpassungen in der ERP Config nutzen

### ISSUE THREAD

**Issue by maximilianruesch** [pickware/shopware-platform#20]

**Comment by maximilianruesch** [comment]
Zugehöriger Pull Request an Shopware:

https://github.com/shopware/platform/pull/1763

**Comment by maximilianruesch** [comment]
Oben genannter PR wurde zugunsten einer allgemeinen Lösung, die wahrscheinlich beim nächsten Major Release (also wahrscheinlich 6.5) mit Shopware kommt, geschlossen. Diese allgemeine Lösung muss anschließend in unserer Config angepasst werden.

**Comment by hanneswernery** [comment]
(falsches repo btw. Das sollte in pickware/shopware-plugins)

**Comment by hanneswernery** [comment]
https://github.com/pickware/shopware-plugins/issues/1955 ist gemergt. Daher kann das issue nun bearbeitet werden.

**Comment by hanneswernery** [comment]
Closed, für issue im korrekten Repo: https://github.com/pickware/shopware-plugins/issues/1969
