### ISSUE TITLE
Überall wieder `shopware/core` neusten Stand requiren anstatt `shopware/platform` (mit Hannes fix)

### ISSUE THREAD

**Issue by hanneswernery** [pickware/shopware-platform#25]

**Comment by hanneswernery** [comment]
Der fix wurde gemergt; wir können also unseren workaround (shopware/platform branch requiren) entfernen und wieder "normal" core, administration, etc requiren 👍

**Comment by hanneswernery** [comment]
> https://github.com/pickware/shopware-plugins/pull/3913 required wieder shopware/core

Sollten definitiv 2 separate PRs sein

**Comment by Ceddy610** [comment]
@hanneswernery ich mach den separaten PR mit den Changes auf
